@API_URL = http://localhost:5000

### HOMEPAGE
GET {{API_URL}}/

### LOGIN
POST {{API_URL}}/login
Content-Type: application/json

{
  "email": "u1@u1.com",
  "password": "u1"
}

### PROTECTED RESOURCE
GET {{API_URL}}/books
Content-Type: application/json

### LOGOUT
GET {{API_URL}}/logout
